### PR TITLE
Meal add and edit meal - only recipe 

### PR DESCRIPTION
**Pull request by Hitarth-Kothari**

### CODE REVIEW

**Review by nidal312 — DISMISSED** [review]
App crashes when giving a date with the default 'Recipe' item

Alos, when you try to align add button with the rest of the activitites

**Comment by Hitarth-Kothari** [comment]
fixed the crashing part, i dont understand the button part
if we are making a scrollview, everything should fit right?

**Comment by Hitarth-Kothari** [comment]
button alligned with rest

**Comment by gokul887** [comment]
1. The sizing of both the inputs are off
2. App crashes on invalid input
3. Disable the recipe option of the spinner. User should not be able to select

**Comment by Hitarth-Kothari** [comment]
> 1. The sizing of both the inputs are off
> 2. App crashes on invalid input
> 3. Disable the recipe option of the spinner. User should not be able to select

Solved
1 > made size changes
2 > using a date picker now to make sure input is valid
3 > error msg when date or recipe is invalid

**Review by gokul887 — APPROVED** [review]

**Pull request merged**
